version: "3.8"

services:
  mysql_container:
    image: mysql:8.0
    container_name: mysql_cont
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: demodb
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./DATABASE/init.sql:/docker-entrypoint-initdb.d/init.sql

  flask_container:
    build: ./BACKEND
    container_name: flask_cont
    restart: always
    depends_on:
      mysql_container:
        condition: service_healthy
    ports:
      - "5000:5000"
